### ISSUE TITLE
heroku add on 문제

### ISSUE THREAD

**Issue by hou27** [hou27/bookmark-backend#53]
add on 2개 이상부터는 유료라 redis add on을 추가하지 못하는 상황

**Comment by hou27** [comment]
aws로 배포할 에정

**Comment by hou27** [comment]
ecs 문제로 인해 일단 ec2로 직접 배포해둠

**Comment by hou27** [comment]
aws ec2에 docker-compose를 사용하여 배포함
```yaml
version: '2'

services:
  redis: # Name of container
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - shared-network
  postgres: # Name of container
    image: postgres:alpine
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5432:5432
    networks:
      - shared-network
  api:
    image: hou27/bookmark_backend:0.1.1
    networks:
      - shared-network
    env_file:
      - .env.prod
    ports:
      - 4000:4000
    depends_on:
      - redis
      - postgres
networks:
  shared-network:
    driver: bridge
```
